//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 10:28:58 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:9090/ws/ms-office-details", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package home.estore.msoffice;
